name: TestingNocache
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - name: Setup abcd
    #   run: |
    #     sudo apt-get update
    - name: Setup Cloudflared222
      env:
          GT: ${{ secrets.GT }}
          AC1: ${{ secrets.AC1 }}
          AC1_P: ${{ secrets.AC1_P }}
          AC2: ${{ secrets.AC2 }}
          AC2_P: ${{ secrets.AC2_P }}
          AC3: ${{ secrets.AC3 }}
          AC3_P: ${{ secrets.AC3_P }}
          GT_2: ${{ secrets.GT_2 }}
          AC4: ${{ secrets.AC4 }}
          AC4_P: ${{ secrets.AC4_P }}
      run: |
        # git clone https://${GT}@github.com/locionic/shortsmemes-anime ShortsMemes
        # cd ShortsMemes
        # pip install -r requirements.txt
        # python setup.py
        # chmod +x run.sh
        # ./run.sh ${AC1} ${AC1_P} ${AC2} ${AC2_P}
        # cd ../
        git clone https://${GT}@github.com/locionic/Short-Video-Auto-Generation ShortVideo
        cd ShortVideo
        chmod +x run.sh
        ./run.sh ${AC3} ${AC3_P}
        # cd ../
        # git clone https://${GT_2}@github.com/hongloc/MoneyPrinterV2
        # cd MoneyPrinterV2
        # chmod +x setup.sh
        # ./setup.sh ${AC4} ${AC4_P}
